version: '3'
services:
  web:
    build: ./web-app   
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  machine-learning-client:
    build:
      context: ./machine-learning-client
    ports:
      - "8000:8000"