name: Build and Test web-app

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        options: --privileged

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        cd web-app
        docker-compose up --build -d
      
#    - name: Run tests
     # run: |
      #  pytest web_app/tests

