name: Build and Test web-app

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t web-app .

    - name: Run tests
      run: docker run web-app python -m unittest discover -s tests -p '*_test.py'
