name: Build and Test ML Client

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Run ML Client
      run: |
        cd machine-learning-client
        docker-compose up --build -d
      working-directory: .

    - name: Run tests
      run: |
        cd machine_learning_client
        docker build -t mltest -f tests/Dockerfile.tests . && docker run mltest

