name: Deploy to DigitalOcean

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Docker Login and Deploy
        run: |
          echo "${{secrets.DO_TOKEN}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          ls
#          cd 4-containerized-app-exercise-plant4/
#          docker-compose pull
#          docker-compose down
