name: Deploy ML Client to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Log in to Digital Ocean Container Registry
      run: echo ${{ secrets.DO_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Deploy ML Client to Digital Ocean
      run: |
        cd machine-learning-client
        docker-compose down
        docker-compose -f docker-compose.prod.yml up --build -d