name: check lint and format
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies for machine
        if: ${{ hashFiles('machine/**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          cd machine
          pipenv install --dev
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy

      - name: Format with black (machine)
        if: ${{ hashFiles('machine_learning_client/**/*.py') != '' }}
        run: |
          cd machine_learning_client
          pipenv run black .

      - name: Lint with pylint (machine_learning_client)
        if: ${{ hashFiles('machine_learning_client/**/*.py') != '' }}
        run: |
          cd machine
          pipenv run autopep8 --recursive --in-place --aggressive .
          pipenv run isort .
          pipenv run pylint **/*.py

      - name: Install dependencies for webapp
        if: ${{ hashFiles('webapp/**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          cd webapp
          pipenv install --dev
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy

      - name: Format with black (webapp)
        if: ${{ hashFiles('webapp/**/*.py') != '' }}
        run: |
          cd webapp
          pipenv run black .

      - name: Lint with pylint (webapp)
        if: ${{ hashFiles('webapp/**/*.py') != '' }}
        run: |
          cd webapp
          pipenv run autopep8 --recursive --in-place --aggressive .
          pipenv run isort .
          pipenv run pylint **/*.py
