name: check lint and format
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # python -m pip install pipenv
          # pipenv sync --dev --python $(which python)
          # pipenv shell --fancy --python $(which python)
      - name: Format with black
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          black **/*.py

      - name: Lint with pylint
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pylint **/*.py
